### ISSUE TITLE
"Download of browser failed"

### ISSUE THREAD

**Issue by Marviel** [m1guelpf/browser-agent#3]
% browser-agent "what day is it"
Error: Download of browser failed

Caused by:
    0: Failed to create archive file
    1: No such file or directory (os error 2)
 %

**Comment by zouvier** [comment]
I'm having the same issue

**Comment by zouvier** [comment]
@Marviel Solved it. you need to create the following folders in the root directory:

browser
user_data

**Comment by Marviel** [comment]
Nice, seems like that would be an easy PR fix

**Comment by zouvier** [comment]
yeah, tagging @m1guelpf and @refcell  for the fix on their repo's

**Comment by m1guelpf** [comment]
Shouldn't this be fixed by #1?

**Comment by Marviel** [comment]
Haven't tested today -- possibly

**Comment by zouvier** [comment]
It still fails even with the fix by #1

**Comment by m1guelpf** [comment]
Should be fixed by #4
