### ISSUE TITLE
Browser failed to install

### ISSUE THREAD

**Issue by zacharyfmarion** [m1guelpf/browser-agent#7]
I get the following error after installing using cargo (latest rust + cargo installed):

```
$ browser-agent "what is the capital of hawaii" --include-page-content
Error: Download of browser failed

Caused by:
    0: Failed to create archive file
    1: No such file or directory (os error 2)
```

This is on `cargo 1.68.2 (6feb7c9cf 2023-03-26)`

**Comment by chand1012** [comment]
#3 fixed this for me!

**Comment by m1guelpf** [comment]
Should be fixed by https://github.com/m1guelpf/browser-agent/pull/4
